### ISSUE TITLE
Would this firmware run on the Arduino due?

### ISSUE THREAD

**Issue by Jieiku** [CraigMarkwardt/emontx3-continuous#2]
Specifically, is this part possible on the Due:
Inputs are sampled continuously using the interrupt-driven Atmel free-running mode

I am running the Arduino Due in 12bit mode instead of 10bit using: analogReadResolution(ADC_BITS);

On my Arduino Due I use a w5500 ethernet module, and can handle rewriting that part. I just was not sure if its possible to continuously sample on the Arduino Due.

**Comment by CraigMarkwardt** [comment]
Although it's possible this concept could work on Arduino Due, the Due has a completely different architecture.  A bunch of research - and code rewriting - would be required to find out if the processor has the required ADC sampling methods.  I don't have a Due and I haven't looked into it carefully.

**Comment by Jieiku** [comment]
Very Cool, thank you for the response, appreciate it.
